jdk:
  - oraclejdk22
before_install:
  - curl -JLso versions.properties https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties
  - curl -JLso bin/init.sh https://raw.githubusercontent.com/sireum/kekinian/master/bin/init.sh
  - curl -JLso bin/sireum https://raw.githubusercontent.com/sireum/kekinian/master/bin/sireum
  - chmod +x bin/init.sh bin/sireum
  - SIREUM_NO_SETUP=true bin/init.sh
install:
  - unset JAVA_TOOL_OPTIONS
  - bin/sireum proyek publish --javac "-source,22,-target,22,-encoding,utf8,-XDignore.symbol.file,-Xlint:-options,-Xlint:deprecation,-proc:none" --scalac "-release,22,-deprecation,-Yrangepos,-Ydelambdafy:method,-feature,-unchecked,-Xfatal-warnings,-language:postfixOps" --target jvm . org.sireum.ffm.ros.humble
