// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct action_msgs__msg__GoalInfo {
 *     unique_identifier_msgs__msg__UUID goal_id;
 *     builtin_interfaces__msg__Time stamp;
 * }
 * }
 */
public class action_msgs__msg__GoalInfo {

    action_msgs__msg__GoalInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        unique_identifier_msgs__msg__UUID.layout().withName("goal_id"),
        builtin_interfaces__msg__Time.layout().withName("stamp")
    ).withName("action_msgs__msg__GoalInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout goal_id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("goal_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unique_identifier_msgs__msg__UUID goal_id
     * }
     */
    public static final GroupLayout goal_id$layout() {
        return goal_id$LAYOUT;
    }

    private static final long goal_id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unique_identifier_msgs__msg__UUID goal_id
     * }
     */
    public static final long goal_id$offset() {
        return goal_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unique_identifier_msgs__msg__UUID goal_id
     * }
     */
    public static MemorySegment goal_id(MemorySegment struct) {
        return struct.asSlice(goal_id$OFFSET, goal_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unique_identifier_msgs__msg__UUID goal_id
     * }
     */
    public static void goal_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, goal_id$OFFSET, goal_id$LAYOUT.byteSize());
    }

    private static final GroupLayout stamp$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static final GroupLayout stamp$layout() {
        return stamp$LAYOUT;
    }

    private static final long stamp$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static final long stamp$offset() {
        return stamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static MemorySegment stamp(MemorySegment struct) {
        return struct.asSlice(stamp$OFFSET, stamp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static void stamp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stamp$OFFSET, stamp$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

