// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct action_msgs__srv__CancelGoal_Response {
 *     int8_t return_code;
 *     action_msgs__msg__GoalInfo__Sequence goals_canceling;
 * }
 * }
 */
public class action_msgs__srv__CancelGoal_Response {

    action_msgs__srv__CancelGoal_Response() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gen_h.C_CHAR.withName("return_code"),
        MemoryLayout.paddingLayout(7),
        action_msgs__msg__GoalInfo__Sequence.layout().withName("goals_canceling")
    ).withName("action_msgs__srv__CancelGoal_Response");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte return_code$LAYOUT = (OfByte)$LAYOUT.select(groupElement("return_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t return_code
     * }
     */
    public static final OfByte return_code$layout() {
        return return_code$LAYOUT;
    }

    private static final long return_code$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t return_code
     * }
     */
    public static final long return_code$offset() {
        return return_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t return_code
     * }
     */
    public static byte return_code(MemorySegment struct) {
        return struct.get(return_code$LAYOUT, return_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t return_code
     * }
     */
    public static void return_code(MemorySegment struct, byte fieldValue) {
        struct.set(return_code$LAYOUT, return_code$OFFSET, fieldValue);
    }

    private static final GroupLayout goals_canceling$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("goals_canceling"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * action_msgs__msg__GoalInfo__Sequence goals_canceling
     * }
     */
    public static final GroupLayout goals_canceling$layout() {
        return goals_canceling$LAYOUT;
    }

    private static final long goals_canceling$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * action_msgs__msg__GoalInfo__Sequence goals_canceling
     * }
     */
    public static final long goals_canceling$offset() {
        return goals_canceling$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * action_msgs__msg__GoalInfo__Sequence goals_canceling
     * }
     */
    public static MemorySegment goals_canceling(MemorySegment struct) {
        return struct.asSlice(goals_canceling$OFFSET, goals_canceling$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * action_msgs__msg__GoalInfo__Sequence goals_canceling
     * }
     */
    public static void goals_canceling(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, goals_canceling$OFFSET, goals_canceling$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

