// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__srv__DescribeParameters_Response {
 *     rcl_interfaces__msg__ParameterDescriptor__Sequence descriptors;
 * } DescribeParameters_Response
 * }
 */
public class DescribeParameters_Response extends rcl_interfaces__srv__DescribeParameters_Response {

    DescribeParameters_Response() {
        // Should not be called directly
    }
}

