// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__srv__GetParameters_Request {
 *     rosidl_runtime_c__String__Sequence names;
 * } GetParameters_Request
 * }
 */
public class GetParameters_Request extends rcl_interfaces__srv__GetParameters_Request {

    GetParameters_Request() {
        // Should not be called directly
    }
}

