// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__srv__GetParameterTypes_Response {
 *     rosidl_runtime_c__uint8__Sequence types;
 * } GetParameterTypes_Response
 * }
 */
public class GetParameterTypes_Response extends rcl_interfaces__srv__GetParameterTypes_Response {

    GetParameterTypes_Response() {
        // Should not be called directly
    }
}

