// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__srv__ListParameters_Request {
 *     rosidl_runtime_c__String__Sequence prefixes;
 *     uint64_t depth;
 * } ListParameters_Request
 * }
 */
public class ListParameters_Request extends rcl_interfaces__srv__ListParameters_Request {

    ListParameters_Request() {
        // Should not be called directly
    }
}

