// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__msg__ParameterDescriptor__Sequence {
 *     rcl_interfaces__msg__ParameterDescriptor *data;
 *     size_t size;
 *     size_t capacity;
 * } ParameterDescriptor__Sequence
 * }
 */
public class ParameterDescriptor__Sequence extends rcl_interfaces__msg__ParameterDescriptor__Sequence {

    ParameterDescriptor__Sequence() {
        // Should not be called directly
    }
}

