// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__msg__ParameterValue {
 *     uint8_t type;
 *     bool bool_value;
 *     int64_t integer_value;
 *     double double_value;
 *     rosidl_runtime_c__String string_value;
 *     rosidl_runtime_c__octet__Sequence byte_array_value;
 *     rosidl_runtime_c__boolean__Sequence bool_array_value;
 *     rosidl_runtime_c__int64__Sequence integer_array_value;
 *     rosidl_runtime_c__double__Sequence double_array_value;
 *     rosidl_runtime_c__String__Sequence string_array_value;
 * } ParameterValue
 * }
 */
public class ParameterValue extends rcl_interfaces__msg__ParameterValue {

    ParameterValue() {
        // Should not be called directly
    }
}

