// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__msg__Parameter {
 *     rosidl_runtime_c__String name;
 *     rcl_interfaces__msg__ParameterValue value;
 * } Parameter
 * }
 */
public class Parameter extends rcl_interfaces__msg__Parameter {

    Parameter() {
        // Should not be called directly
    }
}

