// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__msg__ParameterDescriptor {
 *     rosidl_runtime_c__String name;
 *     uint8_t type;
 *     rosidl_runtime_c__String description;
 *     rosidl_runtime_c__String additional_constraints;
 *     bool read_only;
 *     bool dynamic_typing;
 *     rcl_interfaces__msg__FloatingPointRange__Sequence floating_point_range;
 *     rcl_interfaces__msg__IntegerRange__Sequence integer_range;
 * } ParameterDescriptor
 * }
 */
public class ParameterDescriptor extends rcl_interfaces__msg__ParameterDescriptor {

    ParameterDescriptor() {
        // Should not be called directly
    }
}

