// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_variant_s {
 *     bool *bool_value;
 *     int64_t *integer_value;
 *     double *double_value;
 *     char *string_value;
 *     rcl_byte_array_t *byte_array_value;
 *     rcl_bool_array_t *bool_array_value;
 *     rcl_int64_array_t *integer_array_value;
 *     rcl_double_array_t *double_array_value;
 *     rcutils_string_array_t *string_array_value;
 * } rcl_variant_t
 * }
 */
public class rcl_variant_t extends rcl_variant_s {

    rcl_variant_t() {
        // Should not be called directly
    }
}

