// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_byte_array_s {
 *     uint8_t *values;
 *     size_t size;
 * } rcl_byte_array_t
 * }
 */
public class rcl_byte_array_t extends rcl_byte_array_s {

    rcl_byte_array_t() {
        // Should not be called directly
    }
}

