// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_node_options_s {
 *     rcl_allocator_t allocator;
 *     bool use_global_arguments;
 *     rcl_arguments_t arguments;
 *     bool enable_rosout;
 *     rmw_qos_profile_t rosout_qos;
 * } rcl_node_options_t
 * }
 */
public class rcl_node_options_t extends rcl_node_options_s {

    rcl_node_options_t() {
        // Should not be called directly
    }
}

