// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef rcutils_error_string_t rcl_error_string_t
 * }
 */
public class rcl_error_string_t extends rcutils_error_string_s {

    rcl_error_string_t() {
        // Should not be called directly
    }
}

