// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef rmw_topic_endpoint_info_array_t rcl_topic_endpoint_info_array_t
 * }
 */
public class rcl_topic_endpoint_info_array_t extends rmw_topic_endpoint_info_array_s {

    rcl_topic_endpoint_info_array_t() {
        // Should not be called directly
    }
}

