// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_event_s {
 *     rcl_event_impl_t *impl;
 * } rcl_event_t
 * }
 */
public class rcl_event_t extends rcl_event_s {

    rcl_event_t() {
        // Should not be called directly
    }
}

