// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rcl_time_jump_s {
 *     rcl_clock_change_t clock_change;
 *     rcl_duration_t delta;
 * }
 * }
 */
public class rcl_time_jump_s {

    rcl_time_jump_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gen_h.C_INT.withName("clock_change"),
        MemoryLayout.paddingLayout(4),
        rcl_duration_s.layout().withName("delta")
    ).withName("rcl_time_jump_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt clock_change$LAYOUT = (OfInt)$LAYOUT.select(groupElement("clock_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rcl_clock_change_t clock_change
     * }
     */
    public static final OfInt clock_change$layout() {
        return clock_change$LAYOUT;
    }

    private static final long clock_change$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rcl_clock_change_t clock_change
     * }
     */
    public static final long clock_change$offset() {
        return clock_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rcl_clock_change_t clock_change
     * }
     */
    public static int clock_change(MemorySegment struct) {
        return struct.get(clock_change$LAYOUT, clock_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rcl_clock_change_t clock_change
     * }
     */
    public static void clock_change(MemorySegment struct, int fieldValue) {
        struct.set(clock_change$LAYOUT, clock_change$OFFSET, fieldValue);
    }

    private static final GroupLayout delta$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("delta"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rcl_duration_t delta
     * }
     */
    public static final GroupLayout delta$layout() {
        return delta$LAYOUT;
    }

    private static final long delta$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rcl_duration_t delta
     * }
     */
    public static final long delta$offset() {
        return delta$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rcl_duration_t delta
     * }
     */
    public static MemorySegment delta(MemorySegment struct) {
        return struct.asSlice(delta$OFFSET, delta$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rcl_duration_t delta
     * }
     */
    public static void delta(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, delta$OFFSET, delta$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

