// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_log_levels_s {
 *     rcl_log_severity_t default_logger_level;
 *     rcl_logger_setting_t *logger_settings;
 *     size_t num_logger_settings;
 *     size_t capacity_logger_settings;
 *     rcl_allocator_t allocator;
 * } rcl_log_levels_t
 * }
 */
public class rcl_log_levels_t extends rcl_log_levels_s {

    rcl_log_levels_t() {
        // Should not be called directly
    }
}

