// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_guard_condition_s {
 *     rcl_context_t *context;
 *     rcl_guard_condition_impl_t *impl;
 * } rcl_guard_condition_t
 * }
 */
public class rcl_guard_condition_t extends rcl_guard_condition_s {

    rcl_guard_condition_t() {
        // Should not be called directly
    }
}

