// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef action_msgs__srv__CancelGoal_Request rcl_action_cancel_request_t
 * }
 */
public class rcl_action_cancel_request_t extends action_msgs__srv__CancelGoal_Request {

    rcl_action_cancel_request_t() {
        // Should not be called directly
    }
}

