// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_lifecycle_transition_s rcl_lifecycle_transition_t
 * }
 */
public class rcl_lifecycle_transition_t extends rcl_lifecycle_transition_s {

    rcl_lifecycle_transition_t() {
        // Should not be called directly
    }
}

