// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_jump_threshold_s {
 *     bool on_clock_change;
 *     rcl_duration_t min_forward;
 *     rcl_duration_t min_backward;
 * } rcl_jump_threshold_t
 * }
 */
public class rcl_jump_threshold_t extends rcl_jump_threshold_s {

    rcl_jump_threshold_t() {
        // Should not be called directly
    }
}

