// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_context_s {
 *     rcl_arguments_t global_arguments;
 *     rcl_context_impl_t *impl;
 *     uint8_t instance_id_storage[8];
 * } rcl_context_t
 * }
 */
public class rcl_context_t extends rcl_context_s {

    rcl_context_t() {
        // Should not be called directly
    }
}

