// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef bool (*rclc_parameter_callback_t)(const Parameter *, const Parameter *, void *)
 * }
 */
public class rclc_parameter_callback_t {

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        boolean apply(MemorySegment old_param, MemorySegment new_param, MemorySegment context);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        gen_h.C_BOOL,
        gen_h.C_POINTER,
        gen_h.C_POINTER,
        gen_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = gen_h.upcallHandle(rclc_parameter_callback_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(rclc_parameter_callback_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static boolean invoke(MemorySegment funcPtr,MemorySegment old_param, MemorySegment new_param, MemorySegment context) {
        try {
            return (boolean) DOWN$MH.invokeExact(funcPtr, old_param, new_param, context);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

