// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcutils_array_list_s {
 *     struct rcutils_array_list_impl_s *impl;
 * } rcutils_array_list_t
 * }
 */
public class rcutils_array_list_t extends rcutils_array_list_s {

    rcutils_array_list_t() {
        // Should not be called directly
    }
}

