// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcutils_hash_map_s {
 *     struct rcutils_hash_map_impl_s *impl;
 * } rcutils_hash_map_t
 * }
 */
public class rcutils_hash_map_t extends rcutils_hash_map_s {

    rcutils_hash_map_t() {
        // Should not be called directly
    }
}

