// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcutils_allocator_s {
 *     void *(*allocate)(size_t, void *);
 *     void (*deallocate)(void *, void *);
 *     void *(*reallocate)(void *, size_t, void *);
 *     void *(*zero_allocate)(size_t, size_t, void *);
 *     void *state;
 * } rcutils_allocator_t
 * }
 */
public class rcutils_allocator_t extends rcutils_allocator_s {

    rcutils_allocator_t() {
        // Should not be called directly
    }
}

