// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcutils_log_location_s {
 *     const char *function_name;
 *     const char *file_name;
 *     size_t line_number;
 * } rcutils_log_location_t
 * }
 */
public class rcutils_log_location_t extends rcutils_log_location_s {

    rcutils_log_location_t() {
        // Should not be called directly
    }
}

