// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rcutils_error_string_s {
 *     char str[1024];
 * }
 * }
 */
public class rcutils_error_string_s {

    rcutils_error_string_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(1024, gen_h.C_CHAR).withName("str")
    ).withName("rcutils_error_string_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout str$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("str"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char str[1024]
     * }
     */
    public static final SequenceLayout str$layout() {
        return str$LAYOUT;
    }

    private static final long str$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char str[1024]
     * }
     */
    public static final long str$offset() {
        return str$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char str[1024]
     * }
     */
    public static MemorySegment str(MemorySegment struct) {
        return struct.asSlice(str$OFFSET, str$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char str[1024]
     * }
     */
    public static void str(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, str$OFFSET, str$LAYOUT.byteSize());
    }

    private static long[] str$DIMS = { 1024 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char str[1024]
     * }
     */
    public static long[] str$dimensions() {
        return str$DIMS;
    }
    private static final VarHandle str$ELEM_HANDLE = str$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char str[1024]
     * }
     */
    public static byte str(MemorySegment struct, long index0) {
        return (byte)str$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char str[1024]
     * }
     */
    public static void str(MemorySegment struct, long index0, byte fieldValue) {
        str$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

