// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_event_s {
 *     const char *implementation_identifier;
 *     void *data;
 *     rmw_event_type_t event_type;
 * } rmw_event_t
 * }
 */
public class rmw_event_t extends rmw_event_s {

    rmw_event_t() {
        // Should not be called directly
    }
}

