// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_names_and_types_s {
 *     rcutils_string_array_t names;
 *     rcutils_string_array_t *types;
 * } rmw_names_and_types_t
 * }
 */
public class rmw_names_and_types_t extends rmw_names_and_types_s {

    rmw_names_and_types_t() {
        // Should not be called directly
    }
}

