// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_qos_incompatible_event_status_s {
 *     int32_t total_count;
 *     int32_t total_count_change;
 *     rmw_qos_policy_kind_t last_policy_kind;
 * } rmw_qos_incompatible_event_status_t
 * }
 */
public class rmw_qos_incompatible_event_status_t extends rmw_qos_incompatible_event_status_s {

    rmw_qos_incompatible_event_status_t() {
        // Should not be called directly
    }
}

