// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_gid_s {
 *     const char *implementation_identifier;
 *     uint8_t data[24];
 * } rmw_gid_t
 * }
 */
public class rmw_gid_t extends rmw_gid_s {

    rmw_gid_t() {
        // Should not be called directly
    }
}

