// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_security_options_s {
 *     rmw_security_enforcement_policy_t enforce_security;
 *     char *security_root_path;
 * } rmw_security_options_t
 * }
 */
public class rmw_security_options_t extends rmw_security_options_s {

    rmw_security_options_t() {
        // Should not be called directly
    }
}

