// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rmw_services_s {
 *     size_t service_count;
 *     void **services;
 * }
 * }
 */
public class rmw_services_s {

    rmw_services_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gen_h.C_LONG.withName("service_count"),
        gen_h.C_POINTER.withName("services")
    ).withName("rmw_services_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong service_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("service_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t service_count
     * }
     */
    public static final OfLong service_count$layout() {
        return service_count$LAYOUT;
    }

    private static final long service_count$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t service_count
     * }
     */
    public static final long service_count$offset() {
        return service_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t service_count
     * }
     */
    public static long service_count(MemorySegment struct) {
        return struct.get(service_count$LAYOUT, service_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t service_count
     * }
     */
    public static void service_count(MemorySegment struct, long fieldValue) {
        struct.set(service_count$LAYOUT, service_count$OFFSET, fieldValue);
    }

    private static final AddressLayout services$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("services"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void **services
     * }
     */
    public static final AddressLayout services$layout() {
        return services$LAYOUT;
    }

    private static final long services$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void **services
     * }
     */
    public static final long services$offset() {
        return services$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void **services
     * }
     */
    public static MemorySegment services(MemorySegment struct) {
        return struct.get(services$LAYOUT, services$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void **services
     * }
     */
    public static void services(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(services$LAYOUT, services$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

