// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_context_s {
 *     uint64_t instance_id;
 *     const char *implementation_identifier;
 *     rmw_init_options_t options;
 *     size_t actual_domain_id;
 *     rmw_context_impl_t *impl;
 * } rmw_context_t
 * }
 */
public class rmw_context_t extends rmw_context_s {

    rmw_context_t() {
        // Should not be called directly
    }
}

