// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_events_s {
 *     size_t event_count;
 *     void **events;
 * } rmw_events_t
 * }
 */
public class rmw_events_t extends rmw_events_s {

    rmw_events_t() {
        // Should not be called directly
    }
}

