// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef rcutils_uint8_array_t rmw_serialized_message_t
 * }
 */
public class rmw_serialized_message_t extends rcutils_uint8_array_s {

    rmw_serialized_message_t() {
        // Should not be called directly
    }
}

