// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_topic_endpoint_info_s {
 *     const char *node_name;
 *     const char *node_namespace;
 *     const char *topic_type;
 *     rmw_endpoint_type_t endpoint_type;
 *     uint8_t endpoint_gid[24];
 *     rmw_qos_profile_t qos_profile;
 * } rmw_topic_endpoint_info_t
 * }
 */
public class rmw_topic_endpoint_info_t extends rmw_topic_endpoint_info_s {

    rmw_topic_endpoint_info_t() {
        // Should not be called directly
    }
}

