// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_qos_profile_s {
 *     enum rmw_qos_history_policy_e history;
 *     size_t depth;
 *     enum rmw_qos_reliability_policy_e reliability;
 *     enum rmw_qos_durability_policy_e durability;
 *     struct rmw_time_s deadline;
 *     struct rmw_time_s lifespan;
 *     enum rmw_qos_liveliness_policy_e liveliness;
 *     struct rmw_time_s liveliness_lease_duration;
 *     bool avoid_ros_namespace_conventions;
 * } rmw_qos_profile_t
 * }
 */
public class rmw_qos_profile_t extends rmw_qos_profile_s {

    rmw_qos_profile_t() {
        // Should not be called directly
    }
}

