// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rmw_request_id_s {
 *     int8_t writer_guid[16];
 *     int64_t sequence_number;
 * }
 * }
 */
public class rmw_request_id_s {

    rmw_request_id_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(16, gen_h.C_CHAR).withName("writer_guid"),
        gen_h.C_LONG.withName("sequence_number")
    ).withName("rmw_request_id_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout writer_guid$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("writer_guid"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t writer_guid[16]
     * }
     */
    public static final SequenceLayout writer_guid$layout() {
        return writer_guid$LAYOUT;
    }

    private static final long writer_guid$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t writer_guid[16]
     * }
     */
    public static final long writer_guid$offset() {
        return writer_guid$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t writer_guid[16]
     * }
     */
    public static MemorySegment writer_guid(MemorySegment struct) {
        return struct.asSlice(writer_guid$OFFSET, writer_guid$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t writer_guid[16]
     * }
     */
    public static void writer_guid(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, writer_guid$OFFSET, writer_guid$LAYOUT.byteSize());
    }

    private static long[] writer_guid$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int8_t writer_guid[16]
     * }
     */
    public static long[] writer_guid$dimensions() {
        return writer_guid$DIMS;
    }
    private static final VarHandle writer_guid$ELEM_HANDLE = writer_guid$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int8_t writer_guid[16]
     * }
     */
    public static byte writer_guid(MemorySegment struct, long index0) {
        return (byte)writer_guid$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int8_t writer_guid[16]
     * }
     */
    public static void writer_guid(MemorySegment struct, long index0, byte fieldValue) {
        writer_guid$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfLong sequence_number$LAYOUT = (OfLong)$LAYOUT.select(groupElement("sequence_number"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static final OfLong sequence_number$layout() {
        return sequence_number$LAYOUT;
    }

    private static final long sequence_number$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static final long sequence_number$offset() {
        return sequence_number$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static long sequence_number(MemorySegment struct) {
        return struct.get(sequence_number$LAYOUT, sequence_number$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static void sequence_number(MemorySegment struct, long fieldValue) {
        struct.set(sequence_number$LAYOUT, sequence_number$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

