// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_publisher_s {
 *     const char *implementation_identifier;
 *     void *data;
 *     const char *topic_name;
 *     rmw_publisher_options_t options;
 *     bool can_loan_messages;
 * } rmw_publisher_t
 * }
 */
public class rmw_publisher_t extends rmw_publisher_s {

    rmw_publisher_t() {
        // Should not be called directly
    }
}

