// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_guard_conditions_s {
 *     size_t guard_condition_count;
 *     void **guard_conditions;
 * } rmw_guard_conditions_t
 * }
 */
public class rmw_guard_conditions_t extends rmw_guard_conditions_s {

    rmw_guard_conditions_t() {
        // Should not be called directly
    }
}

