// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rmw_offered_deadline_missed_status_s {
 *     int32_t total_count;
 *     int32_t total_count_change;
 * }
 * }
 */
public class rmw_offered_deadline_missed_status_s {

    rmw_offered_deadline_missed_status_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gen_h.C_INT.withName("total_count"),
        gen_h.C_INT.withName("total_count_change")
    ).withName("rmw_offered_deadline_missed_status_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt total_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("total_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t total_count
     * }
     */
    public static final OfInt total_count$layout() {
        return total_count$LAYOUT;
    }

    private static final long total_count$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t total_count
     * }
     */
    public static final long total_count$offset() {
        return total_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t total_count
     * }
     */
    public static int total_count(MemorySegment struct) {
        return struct.get(total_count$LAYOUT, total_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t total_count
     * }
     */
    public static void total_count(MemorySegment struct, int fieldValue) {
        struct.set(total_count$LAYOUT, total_count$OFFSET, fieldValue);
    }

    private static final OfInt total_count_change$LAYOUT = (OfInt)$LAYOUT.select(groupElement("total_count_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t total_count_change
     * }
     */
    public static final OfInt total_count_change$layout() {
        return total_count_change$LAYOUT;
    }

    private static final long total_count_change$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t total_count_change
     * }
     */
    public static final long total_count_change$offset() {
        return total_count_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t total_count_change
     * }
     */
    public static int total_count_change(MemorySegment struct) {
        return struct.get(total_count_change$LAYOUT, total_count_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t total_count_change
     * }
     */
    public static void total_count_change(MemorySegment struct, int fieldValue) {
        struct.set(total_count_change$LAYOUT, total_count_change$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

