// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef rosidl_runtime_c__boolean__Sequence rosidl_runtime_c__bool__Sequence
 * }
 */
public class rosidl_runtime_c__bool__Sequence extends rosidl_runtime_c__boolean__Sequence {

    rosidl_runtime_c__bool__Sequence() {
        // Should not be called directly
    }
}

