// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__srv__SetParameters_Response {
 *     rcl_interfaces__msg__SetParametersResult__Sequence results;
 * } SetParameters_Response
 * }
 */
public class SetParameters_Response extends rcl_interfaces__srv__SetParameters_Response {

    SetParameters_Response() {
        // Should not be called directly
    }
}

