// Generated by jextract

package org.sireum.ffm.ros.humble;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_interfaces__srv__SetParameters_Request {
 *     rcl_interfaces__msg__Parameter__Sequence parameters;
 * } SetParameters_Request
 * }
 */
public class SetParameters_Request extends rcl_interfaces__srv__SetParameters_Request {

    SetParameters_Request() {
        // Should not be called directly
    }
}

